### ISSUE TITLE
Error: Invalid UTF-8 sequence crashing Vercel

### ISSUE THREAD

**Issue by k2xl** [supabase/ssr#67]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
On version 
`"@supabase/ssr": "^0.4.0",`

<img width="682" alt="image" src="https://github.com/user-attachments/assets/5ff07c13-e21e-41e1-a528-2774b32fbba0">
Randomly been getting these errors for my app. Only solution is to destroy my cookies and refresh.

Error: Invalid UTF-8 sequence
    at (node_modules/@supabase/ssr/dist/module/utils/base64url.js:187:0)
    at (node_modules/@supabase/ssr/dist/module/utils/base64url.js:90:0)
    at (node_modules/@supabase/ssr/dist/module/cookies.js:246:30)
    at (node_modules/@supabase/auth-js/dist/module/lib/helpers.js:100:0)
    at (node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:787:0)
    at (node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:768:0)
    at (node_modules/@supabase/auth-js/dist/module/GoTrueClient.js:714:0)

This us a super weird bug where when I visit my website it just literally crashes. However clearing my cookies the website works for a bit then stops.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I do not know how the bug occurs.

## System information

Running on a nextjs app with supabase. My app allows google logins

**Comment by Nishchit14** [comment]
This is happening to me as well on the production app. Need to degrade the version asap.

**Comment by k2xl** [comment]
@Nishchit14 which version did you downgrade? I continuously get this error in production too

**Comment by Nishchit14** [comment]
@k2xl  `@supabase/ssr": "^0.0.10`

**Comment by j4w8n** [comment]
@Nishchit14 @k2xl would you mind adding this option to all of your Supabase client-creation code, to see if it resolves the issue? Keep in mind that this will alter how the cookie is stored; so, if you are grabbing the cookie yourself, somewhere in your code, you'd need to change how that functions.

I'm not offering this as a long-term solution, but rather a test. Although, if it's a client option then it could be used long-term.

```js
/* example only. this option is needed in all code that creates a client. */
export function createClient() {
  return createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookieEncoding: "raw"
    }
  )
}
```

base64:
![image](https://github.com/user-attachments/assets/d8ff625e-3563-4c25-a5f9-5bee1251cb30)

raw:
![image](https://github.com/user-attachments/assets/92f359a5-4937-4292-83a1-d67d649da23d)


Roughly how long is the time between failures?

**Comment by k2xl** [comment]
Trying and will get back to you

**Comment by k2xl** [comment]
Still occurs. Happens an hour or so in

**Comment by j4w8n** [comment]
I'm not sure what would be going on then. I went through every source file, and the only references I can find to base64url.js are when cookies are being encoded using base64 (or for tests).

And you're sure you added that option in every place that a Supabase client is created?

And the error is the same as the original?

**Comment by k2xl** [comment]
@j4w8n I added it to all the createClients that allow me to pass that cookieEncoding

```
  // Create a supabase client on the browser with project's credentials
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookieEncoding: 'raw' }
  );
  ```

```
const cookieStore = cookies();

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookieEncoding: 'raw',
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options });
          } catch (error) {
            // The `set` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: '', ...options });
          } catch (error) {
            // The `delete` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    }
  );```

```Initialization error: Error: Invalid UTF-8 sequence
    at stringFromUTF8 (webpack-internal:///(rsc)/./node_modules/@supabase/ssr/dist/module/utils/base64url.js:195:19)
    at stringFromBase64URL (webpack-internal:///(rsc)/./node_modules/@supabase/ssr/dist/module/utils/base64url.js:98:17)
    ```

**Comment by j4w8n** [comment]
@k2xl that's really strange. Can you verify the cookie is not being stored with a `base64` prefix at the beginning?

**Comment by k2xl** [comment]
Actually  the cookies still do begin with base64…

**Comment by j4w8n** [comment]
@k2xl Is this reproducible during dev on your machine, or is it only during prod on Vercel?

**Comment by k2xl** [comment]
Reproduces on dev and on prod

**Comment by fincha** [comment]
I have the same issue, but it happens to me only on prod... what a shame :(

```
    "@nuxtjs/supabase": "^1.4.1",
```

error stack

```
[nitro] [unhandledRejection] Error: Invalid UTF-8 sequence
    at stringFromUTF8 (/opt/render/project/src/.output/server/node_modules/@supabase/ssr/dist/main/utils/base64url.js:200:19)
    at stringFromBase64URL (/opt/render/project/src/.output/server/node_modules/@supabase/ssr/dist/main/utils/base64url.js:94:17)
    at Object.getItem (/opt/render/project/src/.output/server/node_modules/@supabase/ssr/dist/main/cookies.js:249:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async getItemAsync (/opt/render/project/src/.output/server/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:19)
    at async SupabaseAuthClient.__loadSession (/opt/render/project/src/.output/server/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:800:34)
    at async SupabaseAuthClient._useSession (/opt/render/project/src/.output/server/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:781:28)
    at async SupabaseAuthClient._emitInitialSession (/opt/render/project/src/.output/server/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1218:16)
```

<img width="625" alt="Screenshot 2024-10-17 at 22 50 40" src="https://github.com/user-attachments/assets/5d34101d-fa2a-409f-8cfb-f1b820cae4a2">
<img width="308" alt="Screenshot 2024-10-17 at 22 50 46" src="https://github.com/user-attachments/assets/26ba3f1f-1285-47bf-b43b-436986f218ab">

**Comment by fincha** [comment]
Ok... my bad, I wondered why the first part of the cookie was decodeable and others not, so I combined it 😄 (what a hacker I am) anyway, the string was also decodeable. 

I used this tool to decode: https://base64.guru/converter/decode

and I had this warning:

The character encoding was detected as “ISO-8859-1”, but the algorithm is inaccurate and there is a high probability that this is wrong. Because of this you can get the wrong results. To know for sure, please check the [Character Encoding Detector](https://base64.guru/tools/character-encoding) tool.

at the end of the json I had this

```
uCS£C£#ã33Cs%¢"Â&5öæöçÖ÷W2#¦fÇ6W×Ð
```
<img width="377" alt="Screenshot 2024-10-17 at 23 08 21" src="https://github.com/user-attachments/assets/84dff6ed-9558-4312-8819-269e1fcea7fe">

this will be the issue

**Comment by Krovikan-Vamp** [comment]
My cookies also start with the "base64-" prefix and I have passed the cookieEncoding prop as noted above.
![image](https://github.com/user-attachments/assets/d4d56aee-a417-481d-af17-20df52bd6b9e)

Are there any options other than downgrading the `@supabase/ssr` version?

Clearing the site data always resolves this error, though. After the session times out (an hour or so) I get the same error.
![image](https://github.com/user-attachments/assets/eb6bfd8f-6d81-420f-9a76-937dda3564df)

**Comment by fincha** [comment]
I "fixed" this for me, by deleting all the cookies and this issue never reappear, BUT i think I have an idea why it was present the first time, if you @Krovikan-Vamp could confirm one of this actions for you too, this will be the issue:

- you switched between users and one of the users has more information in token then the other
- you enriched/decreaed amount of information passed by token for single user

my idea is, if token was 4 cookies long, and is suddently 3 or the other way, it crashes, what makes totally sense IMHO.

**Comment by Krovikan-Vamp** [comment]
Hi @fincha, thanks for your insight! I notice the same thing that deleting all cookies resolves the issue; however only temporarily. This issue _always_ comes back after the session times out (3600 seconds) and the user is on a page that checks `supabase.auth.getUser()`

I am not modifying the cookies/JWT via hooks or anything else. I already updated the codebase so I don't want to face any regressions by downgrading to `@supabase/ssr": "^0.0.10` as suggested by @Nishchit14.

Anyone else found a solution to this? If it applies I am authenticating through Azure but have not been able to resolve from that end.

Thanks! 👾🚀

**Comment by j4w8n** [comment]
@Krovikan-Vamp did you get to a point where your first cookie doesn't start with `base64-`?

**Comment by ptts** [comment]
We're having the same issue:

In our case, the auth cookie is split into 3 parts: `token.0`, `token.1` and `token.2`.

The combination of 
- `token.0` + `token.1` is valid base64 ✅ 
- `token.0` + `token.2` is valid base64 ✅ 
- `token.0` + `token.1` + `token.2` is invalid ❌

`token.0` and `token.2` have the same cookie expiry date, so apparently the have been created at the same time, `token.1` has a different expiry date which is dated after the other two tokens.

<img width="890" alt="image" src="https://github.com/user-attachments/assets/72e75685-3d62-4f27-a435-c54c146e8072" />

Maybe Supabase detects that the first part can stay unchanged, only sets the second (`.1`) part and "forgets" to unset the third (`.2`) part?

**Comment by j4w8n** [comment]
> I'm trying to reproduce this locally, with Google OAuth. Any secrets to getting the session large enough to be broken into three cookies? Right now it's only creating two for me.

I was able to add some extra user data.

**Comment by j4w8n** [comment]
@ptts I do find it interesting that your 2nd and 3rd cookies should've been able to be combined.

Your 1st is of size 3216, and then 3013 and 154. That should've only required two cookies, since 3013 and 154 are a total of 3167 - well below the max of 3216.

Right now, my first two cookies are 3216, then another of 1255.

@k2xl @fincha @Nishchit14 @Krovikan-Vamp whenever you have issues, do you see this cookie size anomaly?

**Comment by andreapiso** [comment]
Our users are facing this too - and it's pretty debilitating as it happens very often

**Comment by j4w8n** [comment]
I did find a mechanism in the cookie-chunking logic, to where it's possible to have a "middle" cookie size of less than the typical 3216. After the whole value is encoded with `encodeURIComponent()`, it tries to make sure it's not splitting a character escape sequence between cookie chunks.

All of that to say it's possible to have a couple of cookie sizes that could've been rolled into one cookie, but they were trying to do the above, so the content got split. If that makes sense.

**Comment by yuriipalam** [comment]
Maybe I'm missing something, but it's kind of insane. Any error shouldn't crash the whole app for the user, instead it should show some feedback. But for some reason I cannot handle this error...

**Comment by hf** [comment]
> [@ptts](https://github.com/ptts) I do find it interesting that your 2nd and 3rd cookies should've been able to be combined.
> 
> Your 1st is of size 3216, and then 3013 and 154. That should've only required two cookies, since 3013 and 154 are a total of 3167 - well below the max of 3216.
> 
> Right now, my first two cookies are 3216, then another of 1255.
> 
> [@k2xl](https://github.com/k2xl) [@fincha](https://github.com/fincha) [@Nishchit14](https://github.com/Nishchit14) [@Krovikan-Vamp](https://github.com/Krovikan-Vamp) whenever you have issues, do you see this cookie size anomaly?

This whole discovery points to my suspicion.

Please make sure your setAll method is correct and the middleware in Next.js is per our docs. I hate Next.js with a passion because this should not be a problem but it is due to their artificial limitation that only middleware can set the cookies of a request's response.

**Comment by andreapiso** [comment]
This also happens in sveltekit with everything being the same as the docs apart from setting domain on the cookie. Not a Next.js specific issue.

**Comment by Krovikan-Vamp** [comment]
I ended up using middleware to expire these cookies after 30 mins. Pretty much resolved the issue for me. Let me know if you want to see the code?
 Sent from Proton Mail for iOS 
On Thu, Jan 30, 2025 at 7:34 PM, andreapiso ***@***.***&gt; wrote:   This also happens in sveltekit with everything being the same as the docs apart from setting domain on the cookie. Not a Next.js specific issue. —

**Comment by hf** [comment]
This should fix: https://github.com/supabase/ssr/pull/90

Please don't use `raw` as cookie encoding! You're only hiding the underlying problem. Please check your integration with Supabase especially Next.js middleware!

**Comment by hf** [comment]
> This also happens in sveltekit with everything being the same as the docs apart from setting domain on the cookie. Not a Next.js specific issue.

Can you please share your code? I need to check what's going on exactly.

**Comment by Krovikan-Vamp** [comment]
I've put it into a [gist](https://gist.github.com/Krovikan-Vamp/20f265d5618d1a857bfd740125204bbf) for your reference. I have some extra cookies set that I don't want to modify, so I have an additional `if` to check specific cookie names.

**Comment by hf** [comment]
@Krovikan-Vamp Could you also share the `updateSession` function?

Anyway be careful setting the maxAge like this because some cookies intentionally are set to `0` max age which removes them.

**Comment by thedrkness** [comment]
Hi @hf I created a support ticket with this same error. Support Ticket ID: 20673499054

Could you please take a look. Thank you!

**Comment by robertlansing** [comment]
This is still happening. Here was my workaround that seems successful so far:

`export async function middleware(request: NextRequest) {
  // single response instance for the entire middleware
  const response = NextResponse.next({
    request: { headers: request.headers },
  });

try {
    const supabase = createServerClient<Database>(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
...

  return response;
  } catch (err) {
    /* ---------- graceful recovery ---------- */
    const signinUrl = new URL('/signin', request.url);
    signinUrl.searchParams.set('error', 'Invalid session, please sign in again');
    const redirect = NextResponse.redirect(signinUrl);
    const isApiRoute = request.nextUrl.pathname.startsWith('/api/');

    // delete every Supabase cookie from the redirect response to ensure they're gone
    request.cookies.getAll().forEach(c => {
      if (c.name.startsWith('sb-')) {
        if (isApiRoute) {
          // For API routes, we prepare a 401 response with cleared cookies
          response.cookies.set(c.name, '', { maxAge: 0, path: '/' });
        } else {
          // For page routes, we clear cookies on the redirect response
          redirect.cookies.set(c.name, '', { maxAge: 0, path: '/' });
        }
      }
    });

    console.error('Middleware auth error:', {
      message: (err as Error).message,
      path: request.nextUrl.pathname,
      timestamp: new Date().toISOString(),
    });

    // For API routes, return 401 with cleared cookies
    if (isApiRoute) {
      return NextResponse.json(
        { error: 'Invalid session, please sign in again.' },
        { status: 401 }
      );
    }

    // For page routes, redirect to signin with cleared cookies and error message
    return redirect;
  }
}
`

The key being to redirect to the signin path if the cookies cannot be validated for any reason. This also displays a small snackbar  error that the session was invalid. It works for corrupt cookies and other auth issues.

At least it clears cookies and prevents the app from crashing.

**Comment by wong2** [comment]
@egoing That's awesome! Have you found out why there is an additional cookie chunk though?

**Comment by smoglica** [comment]
Happens to me too.

I notice a third cookie chunk when custom jwt claims starts to be longer.

I my case I store in the jwt multiple roles as array of string. This error occurs to me when user starts to have multiple roles.

**Comment by sdocquir** [comment]
I'm running sveltekit + ssr in production. I'm getting the same issue, which is made worst by the fact that this can be used as an attack vector to kill any server that runs @supabase/ssr with `createServerClient()`. 

All that's required is for a malicious client to add an extra cookie chunk with bad data.

**Comment by maxemitchell** [comment]
We hit this in production on `@supabase/ssr@0.6.1` with a malformed SSR auth cookie. The important part is that the crash happens before application code can safely treat the user as unauthenticated, because `createServerClient(...).auth.onAuthStateChange(...)` triggers the initial session load path.

Observed stack shape:

- `@supabase/ssr` cookie storage reads `sb-...-auth-token` / chunked `sb-...-auth-token.0`
- value starts with `base64-`
- `stringFromBase64URL(...)` throws `Invalid UTF-8 sequence`
- the error surfaces during auth initialization / `_emitInitialSession`
- clearing the browser cookie resolves the request

A minimal reproduction for us was renaming/corrupting the session cookie so the server receives something like:

```txt
sb-<project-ref>-auth-token.0=base64-not@base64
```

Expected behavior: malformed cookie storage should be treated as missing/invalid session, not throw out of the server client initialization/session hydration path. Ideally the SSR storage adapter would remove the bad storage item when `setAll` is available, or at least return `null` from `getItem`.

For now, we worked around this at our SvelteKit cookie adapter boundary by preflighting the same chunk/decode path before passing cookies to `createServerClient`:
- `combineChunks(storageKey, ...)`
- if value starts with `base64-`, call `stringFromBase64URL(...)`
- if that throws, set `Max-Age=0` for `storageKey` and chunk-like cookies
- return cookies without those auth entries so the request is unauthenticated

Relevant context:
- PR #90 appears to have attempted a broader chunk handling fix
- PR #100 reverted it
- As of 0.6.1, this crash path still exists

**Comment by swanson8r** [comment]
There's a fix merged 2 weeks ago that may address this issue; see:

- https://github.com/supabase/ssr/pull/210

- https://github.com/supabase/ssr/issues/169
