### ISSUE TITLE
Invalid Base64 characters in auth-token crashes server

### ISSUE THREAD

**Issue by Cikmo** [supabase/ssr#87]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If the auth-token contains an invalid base-64 character, this crashes the server completely, in a non-savable way, when calling getSession. This is a problem because any user can just edit the cookie to crash the server. I'm unable to fix this by using try-catch when calling getSession.

### Error:

```
Error: Invalid Base64-URL character "." at position 2887
    at stringFromBase64URL (/home/project/node_modules/@supabase/ssr/dist/main/utils/base64url.js:103:19)
    at Object.getItem (/home/project/node_modules/@supabase/ssr/dist/main/cookies.js:250:63)
    at async getItemAsync (/home/project/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:19)
    at async SupabaseAuthClient.__loadSession (/home/project/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:815:34)
    at async SupabaseAuthClient._useSession (/home/project/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:796:28)
/home/project/node_modules/@supabase/ssr/dist/main/utils/base64url.js:103
            throw new Error(`Invalid Base64-URL character "${str.at(i)}" at position ${i}`);
                  ^

Error: Invalid Base64-URL character "." at position 2887
    at stringFromBase64URL (/home/project/node_modules/@supabase/ssr/dist/main/utils/base64url.js:103:19)
    at Object.getItem (/home/project/node_modules/@supabase/ssr/dist/main/cookies.js:250:63)
    at async getItemAsync (/home/project/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:19)
    at async SupabaseAuthClient.__loadSession (/home/project/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:815:34)
    at async SupabaseAuthClient._useSession (/home/project/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:796:28)
    at async SupabaseAuthClient._emitInitialSession (/home/project/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1242:16)
```

I **am** able to catch the "throw" error, but, even when I do something later down the road makes the error propegate still. I'm unable to figure out a single place this can be caught on my side.

## To Reproduce

1. Create a auth-token (with correct name), or edit an existing one with a character that is not valid in base-64. For example `.`.
2. Try to access a page that triggers "auth.getSession" to be triggered, with this cookie passed into createServerClient.

## Expected behavior

Invalid base-64 should not crash the server. Should just treat it as unauthorized.

## System information

- OS: Linux
- Version of supabase-js: 2.47.10
- Version of ssr: 0.5.2
- Version of Node.js: 22.12.0

**Comment by Cikmo** [comment]
Please await, I've done some additional testing and the error is not exactly what I thought it was. Will edit and update.

**Comment by Cikmo** [comment]
After a bit of testing, it doesn't even seem like getSession is what triggers it. I'm actually unable to pinpoint what triggers it. All I know is that if a cookie is invalid, the server crashes from the ssr module.

**Comment by Cikmo** [comment]
Okay, I figured out it's the client itself.

After creating:
```typescript
event.locals.supabase = createServerClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
    cookies: {
        getAll: () => event.cookies.getAll(),
        setAll: (cookies) => {
            cookies.forEach(({ name, value, options }) => {
                event.cookies.set(name, value, { ...options, path: '/' });
            });
        }
    }
});
```
it will instantly parse the cookies, and then the error will be raised, however not instantly as it's probably done async behind the scenes. Because of that, try-catch doens't work direcly on this.

I can update this issue to reflect the actual issue tomorrow.

**Comment by hf** [comment]
See this: https://github.com/supabase/ssr/pull/90

**Comment by mandarini** [comment]
related https://github.com/supabase/ssr/issues/169
